### ISSUE TITLE
Error in using multiple GPUs

### ISSUE THREAD

**Issue by ayshrv** [HomeroRR/rmm#3]
Hi, 

I tried running training the Navigator on a multi-gpu setup, but I got some errors.

Basically, I run `python tasks/RMM/train.py --parallelize --gpus G8`

and I got the error
```
Training a seq2seq agent with sample feedback
EPOCH 0
Traceback (most recent call last):
  File "tasks/RMM/train.py", line 572, in <module>
    train_val()
  File "tasks/RMM/train.py", line 568, in train_val
    train( train_env, agent, val_envs, tok)
  File "tasks/RMM/train.py", line 277, in train
    agent.train(interval, feedback=args.agent_feedback_method)
  File "/root/mount/Matterport3DSimulator/tasks/RMM/agent.py", line 686, in train
    self.rollout(speaker_branching=self.train_branching)
  File "/root/mount/Matterport3DSimulator/tasks/RMM/agent.py", line 312, in rollout
    ctx,h_t,c_t = self.encoder(seq, seq_lengths)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.gather(outputs, self.output_device)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 165, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 68, in gather
    res = gather_map(outputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 63, in gather_map
    return type(out)(map(gather_map, zip(*outputs)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/scatter_gather.py", line 55, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/_functions.py", line 68, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/usr/local/lib/python2.7/dist-packages/torch/cuda/comm.py", line 165, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Gather got an input of invalid size: got [2, 51, 512], but expected [2, 139, 512] (gather at /pytorch/torch/csrc/cuda/comm.cpp:231)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f7cc419b193 in /usr/local/lib/python2.7/dist-packages/torch/lib/libc10.so)
frame #1: torch::cuda::gather(c10::ArrayRef<at::Tensor>, long, c10::optional<int>) + 0x2ad (0x7f7bdd54b2ad in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x9e03ad (0x7f7cc93403ad in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x29660b (0x7f7cc8bf660b in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #8: python() [0x4d5909]
frame #11: THPFunction_apply(_object*, _object*) + 0xa8f (0x7f7cc8fc8d2f in /usr/local/lib/python2.7/dist-packages/torch/lib/libtorch_python.so)
frame #14: python() [0x4d5909]
frame #15: python() [0x5312e5]
frame #23: python() [0x4d5a43]
frame #27: python() [0x4d5909]
frame #28: python() [0x4eec9e]
frame #30: python() [0x549cb3]
frame #41: python() [0x4eb32f]
frame #45: __libc_start_main + 0xf0 (0x7f7ccdc85830 in /lib/x86_64-linux-gnu/libc.so.6)
```

Did you train your models on a multi-gpu setup? 
If not, does the codebase in its current state support multi-gpu training?

Note that I was able to start the training without `--parallelize --gpus G8`.

Thanks!

**Comment by HomeroRR** [comment]
Hi Ayush,
Yes, as you point out, there are currently issues with using the DataParallel pytorch module which have not been resolved. As of now all the models have been trained in a single GPU setup. 
Using 1 GPU is the default without the --parallelize or --gpus flags.

**Comment by ayshrv** [comment]
I see. Thanks for letting me know.
